name: CI/CD FastPay

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Usar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test

  docker:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Login en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir imagen Docker
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastpay-app .

    - name: Subir imagen a DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastpay-app

